language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIEFDSQQN6
  secret_access_key:
    secure: AIM0abO3YJkZyduLAQ3oBlVDte1UdVVHGducgvrN+gE4mi5JQD7jsd/kGURTDmkFwEUq9f8cGgBokgz6MJPTG2/bPtz1dWR136R4zTtkxWA/bSPn2Knn4rXORPRDx6gZQXZJ6TEhqmQZKWyJoQOKmwN8dXfUuz+TvGVB9YR3UnVloPNvw8t6H9/KfZv5kN4SfiNVqCuGHQfJrmwbkiEtfMU1BdcZBYUF3W4DmbfuE1DK5vJU0JA2Epk3uSrMMU00hPxrEc6J9V0GDx3wpamxUKMJccNG64MhjruAB3Si0eXNvUDhS0HWMtJNR38hHiAVi1Tq3UBypqELeaie2x3uMEU9vk9DUbgTuKJ6aQyyXxAhZXeJtne70i45f/tE3td8hYbT1MytwAy5qVNDobdkTcWsYTuLQt5diGnG9UKvfkiySRcuf6DvRCbTvacEWpLd1meNl7A6qcHd6xZhtYCRqjB40eM7myF/VL14yiE3e9I+rU+iZYJBHczz1YGRSqYA8UOqRWYjStzMADITTNcQ5dh/ZZ9SquYPBBnh73Hgw8tZM3MVx5Pzj0ztw9gyJkMROlXcrR6ZctedXem0jYQwxCPAatr4jFtQ1E3t7QlkO+SNGISWJqtpuKqdbl0Ekq8ZcHwKRAvSAhVRvqjV6Od7r2S2DX8zZKTDBbmRE6mGif0=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: tb-datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/TB_datadictionary
    all_branches: true
