language: python
python:
- '3.6'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIEFDSQQN6
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: tb-datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/TB_datadictionary
    all_branches: true
  secret_access_key:
    secure: Gr8c2pVdfgPlQMunHp5GhRpPpfUaNJ8k5Lkc09fVJjPjCyEuvtw1mjCXk6U1tu6rbDQNQmfemo9cFMc3j9rrFy3CXg7v6oNmw1hAGGZ+EieDVUiW0XuBWppsYdO377WOh2Zubxl1S9SIGHrA/u0AwMDsJ0GLMRyCkavhhd/coPzRMr9psO4kHXGwSKAyHzObUOg/jOqBDuFVnZt42VcG/BcUd/RzoWpw00dmBoveVsCSI7u2+9XuNgqyQs34ejvpkG2Y4E+YaejFL/WJxOh79BxppXSQSUBSkyYrOr3g4oTCpLCBnPbDT3toIwimHld3CyVuduJjQqeshlRGyUp0HEbGPrVFpFvvLm0q0mBe4u+Z2AAPpr3uID2vrPqZHZnxatBFgRY/c7jcCrQ4MIXGhNlcVC7EBmjNvyzF1kUDG/z/aufsG8gnyy9cDlrET4am/LpK4fjoQydOSa49bLXjUHcF7FaTGacP0giShrqKwmK2VeE+p5QMe5rlFfAIprEASjCnxahAsnY+fi8qL4uS2dIV7Od3NeuBu1ok63CndyV6WjXFslNQFncRlNUOMAQd+XVy20Dxlr2Olf5XS2OO78T9k/gb4G9L/mdMqEtpEfWe6ai/VhI9C54/0MN38+5msTY6Fvnza1u0enJndvMRmPkqaTyh5V5XqSBqk77Paq8=
