language: python
python:
- '2.7'
before_script:
- yes | python setup.py install
- git clone https://github.com/uc-cdis/dictionaryutils; cd dictionaryutils
script:
- "./run_tests.sh"
deploy:
  provider: s3
  access_key_id: AKIAZRNPHKJIEFDSQQN6
  secret_access_key:
    secure: FHMEs+CO3txRF6y/YKiD4sK4fOIe0dy0w9DA1oDKkm28IoVoYbeJGzDmgCcM1YVcx3qLxGNbRK5z++sjzdo8GLbGNiiRQ8jsGkujHVe50gYqclAgCzI/7738q8b22IUw4YOYRBNNcs16DE1s0V8dTBveqMJ1uBq9vHHi8w0HfdX3rwMfUDUxxL0+1brzK0BEmA/EwKCbFm2tkeTW41okA+ba/1OAg38Z9FTzvbvQTW5SZ7Ngoxj7xUYIQKCLsTUvK0xJPnV6nHmuRWt5CLFUV7zLbMReFfMivY2irVXlW2r+NaT4CUyFZM64flyJUiI29jQzPTCXP2pk1PHMbc0F30I2GDtRBEyTXF50O4lsKnjuUAFvO5d2y+nA4XF19d7pxoG+Ymg3DCv/w+z0CG1S0tKYQxrY9xL7GqPGxYPZ6KmA9txPdJ4ammCgrQvBgtsIncbqvm3mBGALnSdmCUelh8PgleXQ/ktYSW/MQuQzvTz9hh+RLZYGCII3udOIr7cManlnI1wIJxiWg3Y5EEwAR/JgnGVyGubgysEh2Ej+nSqEtuWDvde3f8+nx5gVrZLlYBPvKOAEGrMvtZitwDOlqXHEdX9ogHqZ7ASwkWFQCLn9CF6oPS+Geb27uEgKVCFtUCxGw2Jo6qaTUghSVGXlpyffKKWNadlboN4bzmcY+rw=
  bucket: dictionary-artifacts
  local-dir: artifacts
  upload-dir: tb-datadictionary/$TRAVIS_BRANCH
  skip_cleanup: true
  on:
    repo: uc-cdis/TB_datadictionary
    all_branches: true
